spring:
  datasource:
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
  main:
    banner-mode: off

mybatis-plus:
  global-config:
    banner: false
